### ISSUE TITLE
Translate Client

### ISSUE THREAD

**Issue by loonbg** [L-Leite/UnCSO2#1]
Any way to decrypt back encrypted file ? i can try translate client

**Comment by GEEKiDoS** [comment]
The game actually works with unpacked files and only ```1b87c6b551e518d11114ee21b7645a47.pkg``` in Data folder (Nexon client)

--- UPDATE ---
The game works with decompressed VTFs aswell

**Comment by lateleite** [comment]
This program's intention is to extract the contents of CSO2, repacking files is not the aim of this project.

And this is related [cso2-launcher](https://github.com/Ochii/cso2-launcher), not UnCSO2.

There are efforts being made towards using unpacked files with the game. @GEEKiDoS, ReddUT and λnggaraNothing (the latter 2 are from the CSO's wikia discord) are responsible for it
