### ISSUE TITLE
The program crashes when I install the .txt file

### ISSUE THREAD

**Issue by IGNRexI** [L-Leite/UnCSO2#10]
The program crashes when I install the .txt file
interface is very nice

----------------------------------
Errors in Windows Events List
----------------------------------

Error bundle 1766227214907546999, type 4
Event Name: APPCRASH
Answer: Unavailable
Cabin ID: 0

Problem signature:
P1: uc2.exe
P2: 0.0.0.0
P3: 5d9b637e
P4: StackHash_6032
P5: 10.0.18362.418
P6: 99ca0526
P7: c0000374
P8: PCH_FE_FROM_ntdll + 0x000000000009CC14
P9:
P10:

Attached files:
\\? \ C: \ ProgramData \ Microsoft \ Windows \ WR \ Temp \ werb0a3.tmp.dmp
\\? \ C: \ ProgramData \ Microsoft \ Windows \ WR \ Temp \ werb2b8.tmp.werınternalmetadata.xml
\\? \ C: \ ProgramData \ Microsoft \ Windows \ WR \ Temp \ werb2f7.tmp.xml
\\? \ C: \ ProgramData \ Microsoft \ Windows \ WR \ Temp \ werb309.tmp.csv
\\? \ C: \ ProgramData \ Microsoft \ Windows \ WR \ Temp \ werb339.tmp.txt

These files can be found here:
\\? \C:\ProgramData\Microsoft\Windows\WR\reportarchiv to \ appcrash_uc2.exe_b1b5743880c88b20d1f7af89610b93452ffa8f_369f6618_bbae69d0-ff23-4d22-9212-d249b04cb65c

Analysis icon:
Recheck for solution: 0
Report ID: aa6283ad-6915-4f71-8d76-cf4de35b708d
Report Status:
Mixed harness: af7ed77aceee92893882e64b49311d77
Cab Guid: 0

Incorrect application name: uc2.exe, version: 0.0.0.0, timestamp: 0x5d9b637e
Incorrect module name: ntdll.dll, version: 10.0.18362.418, timestamp: 0x99ca0526
Exception code: 0xc0000374
Error distance 0x00000000000f9269
Incorrect process ID: 0x13d8
Application start time: 0x01d58ab0f851a037
Incorrect application path: E:\CSO2Server\debugger\uc2.exe
Incorrect module path: C:\Windows\SYSTEM32\ntdll.dll
Report ID: aa6283ad-6915-4f71-8d76-cf4de35b708d
Incorrect package full name:
Application ID for bad package:

**Comment by lateleite** [comment]
What did you try to extract?

**Comment by IGNRexI** [comment]
i wrote the wrong title sry
The program crashes when I install the .txt file

**Comment by IGNRexI** [comment]
windows 7 8 10 gives the same error
example.txt closes when loading.

**Comment by lateleite** [comment]
I don't understand your problem, I can't open any txt file with UnCSO2

**Comment by IGNRexI** [comment]
+ The program crashes when cstrike extracts the entire folder.

**Comment by lateleite** [comment]
fixed in ac6dff5
