### ISSUE TITLE
UnCSO2 Crashing when attempting to open .pkg files

### ISSUE THREAD

**Issue by TheTechnoGuy18** [L-Leite/UnCSO2#12]
I got a copy of CSO2 from csonline2.net (its their english version). Whenever I try to open its pkg files with this program, UnCSO2 keeps crashing at the very beginning (Windows says ucrtbase.dll is causing the problem). Im sure its something on my side thats causing this. Has anyone else had this issue?

**Comment by lateleite** [comment]
which version on uncso2 did you use?

**Comment by TheTechnoGuy18** [comment]
> which version on uncso2 did you use?

I used a different extractor and that one worked.
Now i have to deal with those compressed vtf files. I dont remember which version I used, i got that from gamebanana.com

**Comment by TheTechnoGuy18** [comment]
Hey man, I downloaded the latest release and that one seems to work just fine!

**Comment by TheTechnoGuy18** [comment]
Nevermind, crashed when extracting again >:(( now libuncso2.dll is causing the problem

**Comment by lateleite** [comment]
try this https://github.com/L-Leite/UnCSO2/releases/tag/v2.0.7

**Comment by TheTechnoGuy18** [comment]
Thanks, now it works!
