### ISSUE TITLE
Program crash / Exit, no error.

### ISSUE THREAD

**Issue by leang97** [L-Leite/UnCSO2#4]
Using UnCSO2 v1.4.4
Tried to unpack .pkg files from cso2_nexon_v24406. 

What I do
Open the program, then go to File > Open Folder and open "Data" directory in cso2_nexon_v24406.
UnCSO2 stuck for awhile and exited without any errors or messages.
Is UnCSO2 working to unpack cso2 korea?

Thanks

**Comment by leang97** [comment]
I tried to cut half of the pkg from the Data folder and move it outside of Data directory,and I tried to open the directory "Data" again, but this time it stuck with "Loading Package Entries".

![image](https://user-images.githubusercontent.com/12026849/52535747-0b9d2f00-2d8d-11e9-9fc9-4e5fc1ca5cbe.png)

**Comment by lateleite** [comment]
Should be fixed in 5980dcd
