### ISSUE TITLE
Compatibility with Taiwanese client

### ISSUE THREAD

**Issue by Raizen09** [L-Leite/UnCSO2#5]
UnCSO2 is incompatible with CSO2 V24407 - Taiwan. Hopefully there's one soon

**Comment by organnerx** [comment]
Please add compatibility with TW, there are content that should be added to KR version. TW version link: https://drive.google.com/drive/folders/18v59RZbruXI3rC5lmfQVoP5Gom8XCAhY?fbclid=IwAR1UX3mELq3juf3BVo8K69wdatpiDQPlUeDU28DZWirad9kem9VypAKef_8
