### ISSUE TITLE
When will we be able to repack these files? Is there still a way to do it?

### ISSUE THREAD

**Issue by quetzalbread** [L-Leite/UnCSO2#7]
I'm modifying the game a bit, I need to repack the entire thing.
Is there a way to do it or can I run it without repacking?

**Comment by lateleite** [comment]
I'm not planning on implementing a repacking feature

**Comment by quetzalbread** [comment]
Why?
If there isn't one, is there an alternative to running the game with my modified files?

**Comment by lateleite** [comment]
I'm looking forwards to make CSO2 load unpacked files only, sometime soon.

I have created [libuncso2](https://github.com/Ochii/libuncso2) to separate the unpacking logic from the GUI, and am currently implementing it in UnCSO2.

I might also implement it in the client launcher, so it unpacks the data on launch so it can be used in the game. Either that or redistribute the unpacked files somewhere, but I don't know the legality of the latter

**Comment by quetzalbread** [comment]
So according to this, that can't be done now?

**Comment by lateleite** [comment]
It should be possible to do, but I think it's a waste of time, since you can load unpacked files in CSO2 with a few byte patches in its code.

EDIT: I haven't done this yet because (the current release of) UnCSO2 is bugged and doesn't decrypt some files .e* files (such as .ecsv or .ecfg) properly.

**Comment by quetzalbread** [comment]
I'm gonna try it if I can, since I really wanna try the content I made for the game.

**Comment by quetzalbread** [comment]
I saw that most csv files got decrypted.

**Comment by lateleite** [comment]
The padding in the end of each file isn't removed, it was talked about in issue #3

**Comment by quetzalbread** [comment]
Does removing pkgs in Data(expect 1b87c6b551e518d11114ee21b7645a47.pkg) work?

**Comment by lateleite** [comment]
Maybe, I couldn't test that any further because of the poorly decrypted files

**Comment by quetzalbread** [comment]
Did you switch to LibreSSL?

**Comment by lateleite** [comment]
No, I'm still using Crypto++. https://github.com/Ochii/libuncso2/blob/master/sources/ciphers/aescipher.cpp#L21

**Comment by quetzalbread** [comment]
That explains why.
