### ISSUE TITLE
Problems when loading TFO data

### ISSUE THREAD

**Issue by lateleite** [L-Leite/UnCSO2#8]
Thanks a lot for this! however I have already found 3 minor and 1 major problem:

The 3 minor being there's 1 file that's 3.25GB in size (it's also the largest file) that causes the program to crash if you attempt to open it.
The program also crashes if you try to open the index file.
.VMT files seem to be coming out either empty or corrupted (Put this under minor as I doubt anyone is gonna use them anyways)
And the 1 major problem being that model files also seem to be coming out either compressed, empty or corrupted, not sure but nothing is recognizing them as a Source model file (Tried them with Crowbar decompiler and spoke with Crowbar's creator about them)

[DL for previously mentioned 3.25GB file]

[DL for previously mentioned 3.25GB file]: https://drive.google.com/file/d/1wIXS_-2SNEVn3wahub94vF-cQ8dhN2gP/view

_Originally posted by @tetTris11 in https://github.com/L-Leite/UnCSO2/issues/6#issuecomment-537992667_

**Comment by lateleite** [comment]
Thanks for your feedback, I should look into this later today.

Meanwhile, could you please share your game's Data folder? I only have a few PKG files and they're not enough to load data by the index.

A 3 de outubro de 2019 16:20:57 WEST, tetTris11 <notifications@github.com> escreveu:
>Thanks a lot for this! however I have already found 3 minor and 1 major
>problem:
>
>The 3 minor being there's 1 file that's 3.25GB in size (it's also the
>largest file) that causes the program to crash if you attempt to open
>it.
>The program also crashes if you try to open the index file.
>.VMT files seem to be coming out either empty or corrupted (Put this
>under minor as I doubt anyone is gonna use them anyways)
>And the 1 major problem being that model files also seem to be coming
>out either compressed, empty or corrupted, not sure but nothing is
>recognizing them as a Source model file (Tried them with Crowbar
>decompiler and spoke with Crowbar's creator about them)
>
>[DL for previously mentioned 3.25GB file]
>
>[DL for previously mentioned 3.25GB file]:
>https://drive.google.com/file/d/1wIXS_-2SNEVn3wahub94vF-cQ8dhN2gP/view
>
>-- 
>You are receiving this because you modified the open/close state.
>Reply to this email directly or view it on GitHub:
>https://github.com/L-Leite/UnCSO2/issues/6#issuecomment-537992667

-- 
Enviado a partir do meu dispositivo Android com o K-9 Mail. Peço desculpa pela brevidade.

_Originally posted by @L-Leite in https://github.com/L-Leite/UnCSO2/issues/6#issuecomment-538008044_

**Comment by tetTris11** [comment]
[Here we are]
It may also be a good idea to get p0358's data folder as well, I had a look at the sample files they posted and compared them to mine and they have a newer version of the game installed.

[Here we are]: https://drive.google.com/file/d/1IvMcqZMmubKdGLYAV9c_9av2t78wj-cx/view

**Comment by lateleite** [comment]
I managed to load the huge PKG file (apparently it's a single shader file).

I'm not pushing a fix yet because when loading the PKG, UnCSO2 loads the PKG to memory.

**Comment by lateleite** [comment]
I opened a pull request to fix some of these issues: #9 

The PR isn't going to fix the VTF or model issues though

**Comment by lateleite** [comment]
@tetTris11 could you give [version 2.0.5](https://github.com/L-Leite/UnCSO2/releases/tag/v2.0.5) a try (whenever it's uploaded by the CI) and report back please?

**Comment by tetTris11** [comment]
Tried it out, both the large file and the index file load perfectly.

**Comment by p0358** [comment]
I tried and it didn't work for me:
![image](https://user-images.githubusercontent.com/5182588/71420658-a71e5200-2676-11ea-8791-66e219c83512.png)
none of the files seem to be unpacked properly for some reason :/
@tetTris11 indeed my game is most likely newer, the installer files from CBT were from 12.2017 (edit: even from 08.2017), but the shipped launcher did check for updates before checking authorization, and I was launching it from time to time, and this way I ended up with game files dated 11.05.2018. I'm not sure if there could had been another update, if there was, I had to miss it. It's also quite possibly the most recent version one could find anywhere, so I'm uploading these files to MEGA right now (which is very slow, if you have any other storage for >17 GB, could try that as well; torrents?)

**Comment by p0358** [comment]
Here's the link to full files: https://mega.nz/#F!5lcU2aTK!WEAdTM59Pz_I43whsCtxig
Also, here are checksums for these files, in case: https://p0358.net/tfo/report.html / https://p0358.net/tfo/tfochecksums.txt

**Comment by p0358** [comment]
@tetTris11 and as for VTFs, VPKTool from cra0 (for original Titanfall) can patch them on export, one workaround idea could be to try using its repacker to pack these files and then unpack
